DROP TABLE USERTAGMOVIE;
DROP TABLE USERRATEMOVIE;
DROP TABLE TAGS;
DROP TABLE MOVIETAGS;
DROP TABLE MOVIEGENRE;
DROP TABLE MOVIEDIRECTOR;
DROP TABLE MOVIECOUNTRY;
DROP TABLE MOVIEACTOR;
DROP TABLE MOVIE;

CREATE TABLE MOVIE (
ID NUMBER(38) NOT NULL, 
TITLE VARCHAR2(300), 
IMDBID NUMBER(38), 
SPANISHTITLE VARCHAR2(300), 
IMDBPICTUREURL VARCHAR2(1024), 
"YEAR" NUMBER(38), 
RTID VARCHAR2(300), 
RTALLCRITICSRATING NUMBER(5, 2),
RTALLCRITICSNUMREVIEWS NUMBER(5, 2),
RTALLCRITICSNUMFRESH NUMBER(5, 2),
RTALLCRITICSNUMROTTEN NUMBER(5, 2),
RTALLCRITICSSCORE NUMBER(5, 2),
RTTOPCRITICSRATING NUMBER(5, 2),
RTTOPCRITICSNUMREVIEWS NUMBER(5, 2),
RTTOPCRITICSNUMFRESH NUMBER(5, 2),
RTTOPCRITICSNUMROTTEN NUMBER(5, 2),
RTTOPCRITICSSCORE NUMBER(5, 2),
RTAUDIENCERATING NUMBER(5, 2),
RTAUDIENCENUMRATINGS NUMBER(38),
RTAUDIENCESCORE NUMBER(5, 2),
RTPICTUREURL VARCHAR2(1024),
PRIMARY KEY (ID));

CREATE TABLE MOVIEACTOR (
MOVIEID NUMBER(38) NOT NULL,
ACTORID VARCHAR2(300) NOT NULL,
ACTORNAME VARCHAR2(300) NOT NULL,
RANKING NUMBER(38),
PRIMARY KEY (MOVIEID, ACTORID));

CREATE TABLE MOVIECOUNTRY (
MOVIEID NUMBER(38) NOT NULL,
COUNTRY VARCHAR2(40) NOT NULL,
PRIMARY KEY (MOVIEID));

CREATE TABLE MOVIEDIRECTOR (
MOVIEID NUMBER(38) NOT NULL,
DIRECTORID VARCHAR2(300) NOT NULL,
DIRECTORNAME VARCHAR2(300) NOT NULL,
PRIMARY KEY (MOVIEID, DIRECTORNAME));

CREATE TABLE MOVIEGENRE (
MOVIEID NUMBER(38) NOT NULL,
GENRE VARCHAR2(128) NOT NULL,
PRIMARY KEY (MOVIEID, GENRE));

CREATE TABLE MOVIETAGS (
MOVIEID NUMBER(38) NOT NULL,
TAGID NUMBER(38) NOT NULL,
TAGWEIGHT NUMBER(38) NOT NULL,
PRIMARY KEY (MOVIEID, TAGID));

CREATE TABLE TAGS (
ID NUMBER(38) NOT NULL, 
"VALUE" VARCHAR2(100) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE USERRATEMOVIE (
USERID NUMBER(38) NOT NULL,
MOVIEID NUMBER(38) NOT NULL,
RATING NUMBER(38),
DATE_DAY NUMBER(38),
DATE_MONTH NUMBER(38),
DATE_YEAR NUMBER(38),
DATE_HOUR NUMBER(38),
DATE_MINUTE NUMBER(38),
DATE_SECOND NUMBER(38),
PRIMARY KEY (MOVIEID, USERID));

CREATE TABLE USERTAGMOVIE (
USERID NUMBER(38) NOT NULL,
MOVIEID NUMBER(38) NOT NULL,
TAGID NUMBER(38) NOT NULL,
DATE_DAY NUMBER(38),
DATE_MONTH NUMBER(38),
DATE_YEAR NUMBER(38),
DATE_HOUR NUMBER(38),
DATE_MINUTE NUMBER(38),
DATE_SECOND NUMBER(38));

CREATE INDEX GENRE_INDEX ON MOVIEGENRE(GENRE);
CREATE INDEX ACTOR_INDEX ON MOVIEACTOR(MOVIEID);
CREATE INDEX DIRECTOR_INDEX ON MOVIEDIRECTOR(MOVIEID);
CREATE INDEX USERTAGMOVIE_INDEX ON USERTAGMOVIE(MOVIEID);
